# generated by git-team, do not modify

#!/bin/sh

# Copyright (C) 2026 Rea Sand

# This file is part of git-team.

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

activation_scope=$(git config --global team.config.activation-scope)

gitconfig_scope_flag=
if [ "${activation_scope}" = "global" ]; then
        gitconfig_scope_flag=--global
fi

status=$(git config ${gitconfig_scope_flag} team.state.status)

if [ "${status}" != "enabled" ]; then
        exit 0
fi

template=$1
commit_source=$2
commit_hash=$3

# see: https://git-scm.com/docs/githooks#_prepare_commit_msg
# message  - git commit -m|-F
# merge    - git merge (unless ff)
# squash   - git merge --squash
# none     - git commit
# commit   - git commit -c|-C|--amend
# template - git commit -t or if commit.template is set

case "${commit_source}" in
"message" | "merge" | "squash" | "commit")
        if grep "Co-authored-by:" ${template}; then
                exit 0
        fi

        printf "\n\n" >> $template
        git config ${gitconfig_scope_flag} --get-all team.state.active-coauthors | while read coauthor; do
                printf "Co-authored-by: $coauthor\n" >> $template
        done
        ;;
*)
        exit 0
esac

exit 0
