# generated by git-team, do not modify

#!/bin/sh

# Copyright (C) 2026 Rea Sand

# This file is part of git-team.

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"$(dirname ${0})/prepare-commit-msg-git-team.sh" "${@}" || exit $?

PREVIOUS_HOOKS_PATH=$(git config --get team.state.previous-hooks-path)
PREVIOUS_GLOBAL_HOOK="${PREVIOUS_HOOKS_PATH}/$(basename ${0})"
if [ -n "${PREVIOUS_HOOKS_PATH}" ] && [ -x "${PREVIOUS_GLOBAL_HOOK}" ]; then
  "${PREVIOUS_GLOBAL_HOOK}" "${@}" && exit 0 || exit $?
fi

REAL_LOCAL_HOOK="$(git rev-parse --show-toplevel)/.git/hooks/$(basename ${0})"
if [ -x "${REAL_LOCAL_HOOK}" ]; then
   "${REAL_LOCAL_HOOK}" "${@}" || exit $?
fi

exit 0
