# generated by git-team, do not modify

#!/bin/sh

REAL_LOCAL_HOOK="$(git rev-parse --show-toplevel)/.git/hooks/$(basename ${0})"

if [ -x "${REAL_LOCAL_HOOK}" ]; then
    "${REAL_LOCAL_HOOK}" "${@}" || exit $?
fi

exit 0
